## Matrix properties

Frobenius Norm

In [1]:
import numpy as np

X = np.array([[1, 2], [3, 4]])

In [2]:
(1**2 + 2**2 + 3**2 + 4**2)**0.5

5.477225575051661

In [3]:
np.linalg.norm(X) #same as vector L2 norm also known as Euclidean norm 

np.float64(5.477225575051661)

In [4]:
# Frobenius norm using pytorch
import torch
X_pt = torch.tensor([[1, 2], [3, 4.]])
torch.norm(X_pt)

tensor(5.4772)

In [5]:
# Frobenius norm using tensorflow
import tensorflow as tf
X_tf = tf.Variable([[1, 2], [3, 4.]])
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.4772257804870605>

### Matrix Multiplication (with a Vector)

In [7]:
A = np.array([[3,4], [5,6], [7,8]])

b = np.array([1,2])

print(A)
print(A.shape)
print(b)
print(b.shape)

[[3 4]
 [5 6]
 [7 8]]
(3, 2)
[1 2]
(2,)


In [ ]:
np.dot(A, b) # technically dot product are between vectors only

array([11, 17, 23])

In [ ]:
A_pt = torch.tensor([[3,4], [5,6], [7,8]])
b_pt = torch.tensor([1,2])

# using pytorch matmul - like dot np.dot() - automatically infers dims in order to perform dot product, matvec, or matrix multiplication
torch.matmul(A_pt, b_pt)

tensor([11, 17, 23])

In [ ]:
A_tf = tf.Variable([[3,4], [5,6], [7,8]])
b_tf = tf.Variable([1,2])

# matvec - matrix vector multiplication
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

### (Matrix-by-)Matrix Multiplication

In [12]:
M1 = np.array([[3,4], [5,6], [7,8]])
M2 = np.array([[1,9], [2,0]])

print(M1)
print(M1.shape)
print(M2)
print(M2.shape)


[[3 4]
 [5 6]
 [7 8]]
(3, 2)
[[1 9]
 [2 0]]
(2, 2)


In [17]:
np.dot(M1, M2)

# Matix Multiplication is not Commutative M1*M2 != M2*M1

array([[11, 27],
       [17, 45],
       [23, 63]])

In [22]:
M1_pt = torch.tensor([[3,4], [5,6], [7,8]])
M2_pt = torch.tensor([[1,9], [2,0]])

print(M1_pt)
print(M2_pt)

tensor([[3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 9],
        [2, 0]])


In [19]:
torch.matmul(M1_pt, M2_pt)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [15]:
M1_tf = tf.Variable([[3,4], [5,6], [7,8]])
M2_tf = tf.Variable([[1,9], [2,0]])

tf.linalg.matmul(M1_tf, M2_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]], dtype=int32)>