## Vectors

1. One-dimensional array of numbers
2. Denoted in lowercase, *italics*, **bold**, eg: ___x___
3. Arranged in an order, so elements can be accessed by its index
    - Each element in vectors are scalars so not bold, eg: second element of ___x___ is _x2_
4. Representing a point in space:
    - Vector of length two represents location in 2D matrix, eg: [_x1_, _x2_] = [_12_, _4_]
    - Length of three represents location in a 3D cube
    - Length of n represents location in _n_-dimentaional tensor

(Rank 1 Tensors) in NumPy

In [1]:
import numpy as np

In [4]:
x = np.array([1, 2, 3]) # type argument is optional, eg: dtype=np.float16
x_f = np.array([1, 2, 3], dtype=np.float16) 
print(x)
print(x_f)

[1 2 3]
[1. 2. 3.]


In [5]:
len(x)

3

In [6]:
x.shape

(3,)

In [7]:
type(x)

numpy.ndarray

In [8]:
# zero indexed
x[0]

np.int64(1)

In [9]:
type(x[0])

numpy.int64

In [10]:
type(x_f[0])

numpy.float16

### Vector Transposition

In [11]:
# Transposing a regular 1-D array has no effect
x_t = x.T
x_t

array([1, 2, 3])

In [12]:
x_t.shape

(3,)

In [13]:
## If we use nested square brackets: "matrix styled"
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [ ]:
y.shape # 1 row, 3 columns - row vector

(1, 3)

In [15]:
# now when we transpose this matrix of length 1, which can be mathematically equivalent to:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [ ]:
y_t.shape # 3 rows, 1 column - column vector

(3, 1)

In [17]:
# column vector can be transposed back to a row vector
y_t.T

array([[25,  2,  5]])

In [18]:
y_t.T.shape

(1, 3)

In [20]:
# zero vector - have no effect if added to another vector
z = np.zeros(3)
z

array([0., 0., 0.])

### Vectors in PyTorch and TensorFlow

In [21]:
import torch
import tensorflow as tf

In [23]:
x_pt = torch.tensor([1, 2, 3])
x_pt

tensor([1, 2, 3])

In [24]:
x_pt.shape

torch.Size([3])

In [25]:
x_tf = tf.Variable([1, 2, 3])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

### $L^2$ Norm



In [28]:
x_l = np.array([25, 2, 5])
x_l

array([25,  2,  5])

In [29]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [30]:
np.linalg.norm(x_l)

np.float64(25.573423705088842)

### $L^1$ Norm

In [31]:
x_l

array([25,  2,  5])

In [32]:
np.abs(25) + np.abs(2) + np.abs(5)

np.int64(32)

### Squared $L^2$ Norm


In [35]:
x_l

array([25,  2,  5])

In [36]:
(25**2 + 2**2 + 5**2)

654

In [37]:
## we will cover tensor multiplication later
np.dot(x_l, x_l)

np.int64(654)

## $L^\infty$ Norm or Max Norm


In [38]:
x_l

array([25,  2,  5])

In [ ]:
np.max([np.abs(25), np.abs(2), np.abs(5)])