### Matrices

- Two-dimesional array of numbers
- Denoted in uppercase *italics* **bold** eg: ***X***
- Height given priority ahead of width in notation, i.e.,: ($n_{row}$, $n_{col}$)
    - if X has three rows and two columns, its shape is (3,2)
- Individual sclar elements denoted in uppercase, italics only
    - Element in top-right corner of matrix ***X*** above would be *$X_{1,2}$*
- Colon represents an entire row or column (in python index start with zero):
    - Left column of matrix ***X*** is *$X_{:,1}$*
    - Middle row of matrix ***X*** is *$X_{2,:}$*

(Rank 2 Tensors) in Numpy

In [1]:
## Use array() to create matrices with nested lists
import numpy as np

X = np.array([[25, 2], [5, 26], [3, 7]])
print(X)

[[25  2]
 [ 5 26]
 [ 3  7]]


In [2]:
X.shape

(3, 2)

In [3]:
X.size

6

In [4]:
# select left column of matrix X (zero-indexed) 
X[:,0]

array([25,  5,  3])

In [5]:
# select middle row of matrix X (zero-indexed)
X[1,:]

array([ 5, 26])

In [6]:
# Another slicing-by-indexing example
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

## Matrices in PyTorch

In [7]:
import torch

X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [8]:
X_pt.shape

torch.Size([3, 2])

In [10]:
# select middle row of matrix X
X_pt[1,:]

tensor([ 5, 26])

In [11]:
# select 2nd column of matrix X
X_pt[:,1]

tensor([ 2, 26,  7])

## Matrices in TensorFlow

In [12]:
import tensorflow as tf


In [13]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [15]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [16]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [18]:
# select middle row of matrix X
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>