## Common Tensor Operations

#### Tensor transposition

- Transpose of scalar is itself, eg: $x^T$ = x
- Transpose of vector, seen earlier, converts column to row (and vice versa)
- Sclar and vector transposition are special cases of matrix transposition
    - Flip axes over main diagonal such that: $(X^T)_{i,j}$ = $X_{j,i}$
    - column j is now row j and row i is now column i

In [4]:
import numpy as np
X = np.array([[25,2],[5, 26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [6]:
# matrix transpose
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [ ]:
# tensor transpose in tensorflow
import tensorflow as tf
X_tf = tf.constant([[25,2],[5, 26],[3,7]])
X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [9]:
tf.transpose(X_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]], dtype=int32)>

In [11]:
# tensor transpose in pytorch
import torch
X_pt = torch.tensor([[25,2],[5, 26],[3,7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [12]:
X_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

### Basic Tensor Arithmatic

adding and multiplying with scalar applies operation to all elements anf tensor shape is retained

In [13]:
X * 2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [14]:
X + 2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In PyTorch

In [15]:
X_pt * 2

tensor([[50,  4],
        [10, 52],
        [ 6, 14]])

In [16]:
X_pt + 2

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [17]:
# python operators are overloaded in pytorch; could alternatively use torch.add, torch.mul, torch.sub
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In TensorFlow

In [18]:
X_tf * 2 + 2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [19]:
tf.add(tf.multiply(X_tf, 2), 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

If two tensors have same size, operations are often by default applied element-wise. This is not **matrix-multiplication**
but it is called Hadamard product or element wise product

Math notation is A $\odot$ X

In [20]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [22]:
A = X + 2
A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [23]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [24]:
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In PyTorch

In [25]:
A_pt = X_pt + 2
A_pt

tensor([[27,  4],
        [ 7, 28],
        [ 5,  9]])

In [26]:
X_pt + A_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [27]:
X_pt * A_pt

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]])

In Tensor Flow

In [28]:
A_tf = X_tf + 2
A_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[27,  4],
       [ 7, 28],
       [ 5,  9]], dtype=int32)>

In [29]:
A_tf + X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [30]:
A_tf * X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[675,   8],
       [ 35, 728],
       [ 15,  63]], dtype=int32)>

### Tensor Reduction

Calculating the sum across all elements of a tensor is a common operation.
- For vector ***x*** of length n, we calculate $\sum_{i=1}^{n}$ $x_i$
- For matix ***X*** of m by n dimentions, we calculate $\sum_{i=1}^{m}$ $\sum_{j=1}^{n}$ $X_{i,j}$

In [31]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [32]:
X.sum()

np.int64(68)

In [33]:
torch.sum(X_pt)

tensor(68)

In [34]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

In [35]:
# can also use axis=0 or axis=1 to specify which dimension to sum over
X.sum(axis=0) # sum over rows

array([33, 35])

In [36]:
X.sum(axis=1) # sum over columns

array([27, 31, 10])

In [37]:
torch.sum(X_pt, dim=0)


tensor([33, 35])

In [38]:
torch.sum(X_pt, dim=1)

tensor([27, 31, 10])

In [39]:
tf.reduce_sum(X_tf, axis=0)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([33, 35], dtype=int32)>

In [40]:
tf.reduce_sum(X_tf, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([27, 31, 10], dtype=int32)>

Many other operations can be applied with reduction along all or a selection of axis, eg:
- maximum
- minimum
- mean
- product

They are fairly straightforward and use less often than summation, so look up the library docs when necessary

### DOT Product

If we have 2 vectors (say, x and y) with the same length n, we can calculate the dot product between them, This is annotated in several different ways including the follwing:

- x . y
- $x^T$ $y$
- <x, y>

Regardless which notation you use, the calculation is the same; we calculate products in an element-wise fashion and then sum reductively across the products to a scalar value. That is: x . y = $\sum^{i=1}_n$ $x_i$ $y_i$

The dot product is ubiquitous in deep learning: It is performed at every artificial neuron in a deep neural network, which may be made up of millions (or orders of magnitude more) of these neurons



In [43]:
x = np.array([25, 2, 5])
y = np.array([0, 1, 2])

In [ ]:
# manually compute the dot product
25 * 0 + 2 * 1 + 5 * 2

12

In [ ]:
# using numpy
np.dot(x, y)

np.int64(12)

In [49]:
# using pytorch
x_pt = torch.tensor([25, 2, 5.])
y_pt = torch.tensor([0, 1, 2.])
torch.dot(x_pt, y_pt)

tensor(12.)

In [51]:
# using tensorflow
x_tf = tf.Variable([25, 2, 5])
y_tf = tf.Variable([0, 1, 2])
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=12>