## Eigendecomposition

The **eigendecomposition** of some matrix $A$ is 

$A = V \Lambda V^{-1}$

Where: 

* As in examples above, $V$ is the concatenation of all the eigenvectors of $A$
* $\Lambda$ (upper-case $\lambda$) is the diagonal matrix diag($\lambda$). Note that the convention is to arrange the lambda values in descending order; as a result, the first eigenvalue (and its associated eigenvector) may be a primary characteristic of the matrix $A$.

In [2]:
import numpy as np

A = np.array([[4, 2],[-5, -3]])
A

array([[ 4,  2],
       [-5, -3]])

In [4]:
lambdas, V = np.linalg.eig(A)
lambdas, V

(array([ 2., -1.]),
 array([[ 0.70710678, -0.37139068],
        [-0.70710678,  0.92847669]]))

In [5]:
Vinv = np.linalg.inv(V)
Vinv

array([[2.3570226 , 0.94280904],
       [1.79505494, 1.79505494]])

In [6]:
Lambda = np.diag(lambdas)
Lambda

array([[ 2.,  0.],
       [ 0., -1.]])

confirm that $A = V \Lambda V^{-1}$

In [7]:
np.dot(np.dot(V, Lambda), Vinv)

array([[ 4.,  2.],
       [-5., -3.]])

Eigendecomposition is not possible with all matrices. And in some cases where it is possible, the eigendecomposition involves complex numbers instead of straightforward real numbers. 

In machine learning, however, we are typically working with real symmetric matrices, which can be conveniently and efficiently decomposed into real-only eigenvectors and real-only eigenvalues. If $A$ is a real symmetric matrix then...

$A = Q \Lambda Q^T$

...where $Q$ is analogous to $V$ from the previous equation except that it's special because it's an orthogonal matrix. 

In [8]:
A = np.array([[2, 1], [1, 2]])
A

array([[2, 1],
       [1, 2]])

In [9]:
lambdas, Q = np.linalg.eig(A)
lambdas, Q

(array([3., 1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [12]:
Q_T = Q.T
Q_T

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [13]:
Lambda = np.diag(lambdas)
Lambda

array([[3., 0.],
       [0., 1.]])

lets confirm $A = Q \Lambda Q^T$

In [14]:
np.dot(np.dot(Q, Lambda), Q_T)

array([[2., 1.],
       [1., 2.]])

(As a quick aside, we can demostrate that $Q$ is an orthogonal matrix because $Q^TQ = QQ^T = I$.)

In [15]:
np.dot(Q, Q_T)

array([[ 1.00000000e+00, -2.23711432e-17],
       [-2.23711432e-17,  1.00000000e+00]])

In [16]:
np.dot(Q_T, Q)

array([[1.00000000e+00, 2.23711432e-17],
       [2.23711432e-17, 1.00000000e+00]])

Exercises:

1. Use PyTorch to decompose the matrix $P$ (below) into its components $V$, $\Lambda$, and $V^{-1}$. Confirm that $P = V \Lambda V^{-1}$.
2. Use PyTorch to decompose the symmetric matrix $S$ (below) into its components $Q$, $\Lambda$, and $Q^T$. Confirm that $S = Q \Lambda Q^T$.

In [17]:
import torch

P = torch.tensor([[25, 2, -5], [3, -2, 1], [5, 7, 4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [18]:
S = torch.tensor([[25, 2, -5], [2, -2, 1], [-5, 1, 4.]])
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [20]:
lambdas, V = torch.linalg.eig(S)
lambdas, V

(tensor([26.2361+0.j,  3.2435+0.j, -2.4796+0.j]),
 tensor([[ 0.9744+0.j,  0.1943+0.j, -0.1132+0.j],
         [ 0.0614+0.j,  0.2548+0.j,  0.9651+0.j],
         [-0.2163+0.j,  0.9473+0.j, -0.2363+0.j]]))

In [21]:
Lambda = torch.diag(lambdas)
Lambda

tensor([[26.2361+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  3.2435+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -2.4796+0.j]])

In [22]:
Vinv = torch.inverse(V)
Vinv

tensor([[ 0.9744+0.j,  0.0614+0.j, -0.2163+0.j],
        [ 0.1943+0.j,  0.2548+0.j,  0.9473+0.j],
        [-0.1132+0.j,  0.9651+0.j, -0.2363+0.j]])

In [23]:
torch.matmul(torch.matmul(V, Lambda), Vinv)

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 2.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [-5.0000+0.j,  1.0000+0.j,  4.0000+0.j]])

In [24]:
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

So by this we can confirm  $P = V \Lambda V^{-1}$. 

In [25]:
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

In [28]:
lambdas, Q = torch.linalg.eig(S)
lambdas, Q

(tensor([26.2361+0.j,  3.2435+0.j, -2.4796+0.j]),
 tensor([[ 0.9744+0.j,  0.1943+0.j, -0.1132+0.j],
         [ 0.0614+0.j,  0.2548+0.j,  0.9651+0.j],
         [-0.2163+0.j,  0.9473+0.j, -0.2363+0.j]]))

In [29]:
Lambda = torch.diag(lambdas)
Lambda

tensor([[26.2361+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  3.2435+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -2.4796+0.j]])

In [30]:
Q_T = torch.transpose(Q, 0, 1)
Q_T

tensor([[ 0.9744+0.j,  0.0614+0.j, -0.2163+0.j],
        [ 0.1943+0.j,  0.2548+0.j,  0.9473+0.j],
        [-0.1132+0.j,  0.9651+0.j, -0.2363+0.j]])

In [31]:
torch.matmul(torch.matmul(Q, Lambda), Q_T)

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 2.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [-5.0000+0.j,  1.0000+0.j,  4.0000+0.j]])

In [32]:
S

tensor([[25.,  2., -5.],
        [ 2., -2.,  1.],
        [-5.,  1.,  4.]])

So by this we can confirm $S = Q \Lambda Q^T$.